# Don't print a new line at the start of the prompt
add_newline = false

prompt_order = [
  "git_branch",
  "git_state",
  "git_status",
]

[git_branch]
style = ""
prefix = ""

[git_state]
style = ""

[git_status]
style = ""
prefix = ""
suffix = ""
show_sync_count = true
deleted = "✕"

